version: '3.8'
services:
  # Service Backend (Golang) - Milik Payad
  backend:
    image: muhammadalfayyadh/server
    container_name: chatbot-server
    environment:
      - GEMINI_API_KEY=AIzaSyBScRrn0BvsSRZsdOGFNNft1YfI_28fCL8
      - GIN_MODE=release
    ports:
      - "8080:8080"
    restart: always
    networks:
      - chatbot-network

  # Service Frontend (Nginx/Web) - Milik Kawan
  frontend:
    # GANTI 'akun_kawan' dengan username asli kawanmu di Docker Hub
    image: muhammadnabilfadhila/chatbot-client
    container_name: chatbot-client
    ports:
      - "80:80"        # Akses via browser di http://localhost
    depends_on:
      - backend
    restart: always
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge