services:
  # Service Backend (Golang) - Milik Payad
  backend:
    # Jika file backend ada di folder './backend', gunakan build. 
    # Jika sudah di-push ke Docker Hub, biarkan baris image saja.
    build: ./server
    image: muhammadalfayyadh/chatbot-backend:v1
    container_name: chatbot-backend
    environment:
      - GEMINI_API_KEY= AIzaSyBP3BGRqqsP5wCxHYJFAfrMVKLEBfO7sH8
      - GIN_MODE=release
    ports:
      - "8080:8080"
    restart: always
    networks:
      - chatbot-network

  # Service Frontend (Nginx/Web) - Milik Kawan
  frontend:
    # Tambahkan baris build di bawah ini sesuai folder frontend kawanmu
    build: ./client 
    image: muhammadnabilfadhila/chatbot-frontend:v1.0
    container_name: chatbot-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge